library(ggplot2)
library(scales)
data <- read.csv("bandwidth-lantern.csv", col.names=c("date", "KBps", "MBps"))
data$date <- as.Date(data$date, format="%m/%d/%Y")

daterange <- seq(min(data$date), max(data$date), "1 week")
data <- data.frame(date=daterange, MBps=data$MBps[match(daterange, data$date)])
p <- ggplot(data, aes(x=date, y=MBps))
p <- p + geom_bar(stat="identity", width=7.1)
p <- p + xlab(NULL) + ylab("MB/s")
p <- p + scale_x_date(labels=date_format("%b %Y"))
p <- p + scale_y_continuous(labels=comma)
p <- p + theme(axis.text=element_text(size=7), axis.title=element_text(size=8), axis.title.x=element_blank())
ggsave("bandwidth-lantern.pdf", p, width=4, height=1.4, units="in")
