library(ggplot2)
library(scales)
data <- read.csv("psiphon3-fronted-meek-unique-users-all-regions.csv", skip=2, col.names=c("date", "clients"))
data$date <- as.Date(data$date, format="%b %d, %Y")

daterange <- seq(min(data$date), max(data$date), "1 day")
data <- data.frame(date=daterange, clients=data$clients[match(daterange, data$date)])
p <- ggplot(data, aes(x=date, y=clients))
p <- p + geom_bar(stat="identity", width=1.1) + xlab(NULL) + ylab("Daily unique users") + scale_x_date(labels=date_format("%b %Y")) + theme(axis.text=element_text(size=7), axis.title=element_text(size=8), axis.title.x=element_blank())
ggsave("clients-psiphon3.pdf", width=4, height=1.4, units="in")
