library(ggplot2)
library(scales)
data <- read.csv("clients-psiphon.csv", col.names=c("proto", "date", "clients"))
data$date <- as.Date(data$date, format="%b %d, %Y")

daterange <- seq(min(data$date), max(data$date), "1 day")
data <- data.frame(date=daterange, clients=data$clients[match(daterange, data$date)])
p <- ggplot(data[data$date>=as.Date("2014-12-07"), ], aes(x=date, y=clients))
p <- p + geom_bar(stat="identity", width=1.1)
p <- p + xlab(NULL) + ylab("Daily unique users")
p <- p + scale_x_date(labels=date_format("%b %Y"))
p <- p + scale_y_continuous(labels=comma)
p <- p + theme(axis.text=element_text(size=7), axis.title=element_text(size=8), axis.title.x=element_blank())
ggsave("clients-psiphon.pdf", p, width=4, height=1.4, units="in")
